name: STREAM_AI
channels:
  - defaults
dependencies:
  - ca-certificates
  - libcxx
  - libffi
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - certifi
      - charset-normalizer
      - coloredlogs
      - contourpy
      - cycler
      - filelock
      - flatbuffers
      - fonttools
      - humanfriendly
      - idna
      - importlib-resources
      - jinja2
      - joblib
      - kiwisolver
      - markupsafe 
      - matplotlib
      - mpmath
      - networkx
      - numpy
      - onnxruntime
      - opencv-python
      - packaging
      - pandas
      - patsy
      - pillow
      - protobuf
      - pyparsing
      - python-dateutil
      - pytz
      - requests
      - scikit-learn
      - scipy
      - six
      - statsmodels
      - sympy
      - threadpoolctl
      - torch
      - torchvision
      - typing-extensions
      - tzdata
      - urllib3
      - zipp