; generated by PrusaSlicer 2.5.0+MacOS-arm64 on 2023-02-14 at 15:37:49 UTC

; 

; external perimeters extrusion width = 1.60mm
; perimeters extrusion width = 1.60mm
; infill extrusion width = 1.60mm
; solid infill extrusion width = 1.60mm
; top infill extrusion width = 1.60mm
; first layer extrusion width = 1.60mm

M107
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.8
G1 Z1.8 F600
G1 E-2 F2400
G92 E0
G1 X82.554 Y82.099 F7800
G1 E2 F2400
;TYPE:Skirt/Brim
;WIDTH:1.6
G1 F600
G1 X84.947 Y80.391 E6.27775
G1 X87.711 Y79.388 E10.5555
G1 X90 Y79.143 E13.9053
G1 X110 Y79.143 E43.00277
G1 X112.913 Y79.542 E47.28052
G1 X115.613 Y80.707 E51.55827
G1 X117.901 Y82.554 E55.83602
G1 X119.609 Y84.947 E60.11377
G1 X120.612 Y87.711 E64.39152
G1 X120.857 Y90 E67.74132
G1 X120.857 Y110 E96.83879
G1 X120.458 Y112.913 E101.11654
G1 X119.293 Y115.613 E105.39429
G1 X117.446 Y117.901 E109.67204
G1 X115.053 Y119.609 E113.94979
G1 X112.289 Y120.612 E118.22754
G1 X110 Y120.857 E121.57735
G1 X90 Y120.857 E150.67481
G1 X87.087 Y120.458 E154.95256
G1 X84.387 Y119.293 E159.23031
G1 X82.099 Y117.446 E163.50806
G1 X80.391 Y115.053 E167.78582
G1 X79.388 Y112.289 E172.06357
G1 X79.143 Y110 E175.41337
G1 X79.143 Y90 E204.51083
G1 X79.542 Y87.087 E208.78859
G1 X80.707 Y84.387 E213.06634
G1 X82.475 Y82.197 E217.16077
G1 X83.58 Y83.184 F7800
G1 F600
G1 X83.954 Y82.765 E217.97785
G1 X86.289 Y81.333 E221.96289
G1 X90 Y80.572 E227.47498
G1 X110 Y80.572 E256.57245
G1 X112.71 Y80.97 E260.55749
G1 X115.191 Y82.13 E264.54253
G1 X117.235 Y83.954 E268.52757
G1 X118.667 Y86.289 E272.51261
G1 X119.428 Y90 E278.02471
G1 X119.428 Y110 E307.12217
G1 X119.03 Y112.71 E311.10721
G1 X117.87 Y115.191 E315.09225
G1 X116.046 Y117.235 E319.07729
G1 X113.711 Y118.667 E323.06233
G1 X110 Y119.428 E328.57443
G1 X90 Y119.428 E357.6719
G1 X87.29 Y119.03 E361.65694
G1 X84.809 Y117.87 E365.64198
G1 X82.765 Y116.046 E369.62702
G1 X81.333 Y113.711 E373.61206
G1 X80.572 Y110 E379.12415
G1 X80.572 Y90 E408.22162
G1 X80.97 Y87.29 E412.20666
G1 X82.13 Y84.809 E416.1917
G1 X83.496 Y83.278 E419.17635
G1 E417.17635 F2400
G92 E0
G1 X109.2 Y109.2 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:1.6
G1 F600
G1 X90.8 Y109.2 E28.76966
G1 X90.8 Y90.8 E55.53932
G1 X109.2 Y90.8 E82.30898
G1 X109.2 Y109.074 E108.89532
G1 X107.714 Y108.414 F7800
;TYPE:Internal infill
;WIDTH:1.6
G1 F600
G1 X107.714 Y91.586 E133.37917
G1 X106.171 Y91.586 F7800
G1 F600
G1 X106.171 Y108.414 E157.86302
G1 X104.629 Y108.414 F7800
G1 F600
G1 X104.629 Y91.586 E182.34687
G1 X103.086 Y91.586 F7800
G1 F600
G1 X103.086 Y108.414 E206.83072
G1 X101.543 Y108.414 F7800
G1 F600
G1 X101.543 Y91.586 E231.31457
G1 X100 Y91.586 F7800
G1 F600
G1 X100 Y108.414 E255.79842
G1 X98.457 Y108.414 F7800
G1 F600
G1 X98.457 Y91.586 E280.28227
G1 X96.914 Y91.586 F7800
G1 F600
G1 X96.914 Y108.414 E304.76612
G1 X95.371 Y108.414 F7800
G1 F600
G1 X95.371 Y91.586 E329.24997
G1 X93.828 Y91.586 F7800
G1 F600
G1 X93.828 Y108.414 E353.73381
G1 X92.286 Y108.414 F7800
G1 F600
G1 X92.286 Y91.586 E378.21766
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.8
G1 Z2.6 F600
G1 E376.21766 F2400
G92 E0
G1 X109.2 Y109.2 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:1.6
G1 F600
G1 X90.8 Y109.2 E28.76966
G1 X90.8 Y90.8 E55.53932
G1 X109.2 Y90.8 E82.30898
G1 X109.2 Y109.074 E108.89532
G1 X108.414 Y107.714 F7800
;TYPE:Internal infill
;WIDTH:1.6
G1 F600
G1 X91.586 Y107.714 E133.37917
G1 X91.586 Y106.171 F7800
G1 F600
G1 X108.414 Y106.171 E157.86302
G1 X108.414 Y104.629 F7800
G1 F600
G1 X91.586 Y104.629 E182.34687
G1 X91.586 Y103.086 F7800
G1 F600
G1 X108.414 Y103.086 E206.83072
G1 X108.414 Y101.543 F7800
G1 F600
G1 X91.586 Y101.543 E231.31457
G1 E229.31457 F2400
G92 E0
G1 X108.414 Y100 F7800
G1 E2 F2400
G1 F600
G1 X91.586 Y100 E26.48385
G1 X91.586 Y98.457 F7800
G1 F600
G1 X108.414 Y98.457 E50.9677
G1 X108.414 Y96.914 F7800
G1 F600
G1 X91.586 Y96.914 E75.45155
G1 X91.586 Y95.371 F7800
G1 F600
G1 X108.414 Y95.371 E99.9354
G1 X108.414 Y93.828 F7800
G1 F600
G1 X91.586 Y93.828 E124.41925
G1 X91.586 Y92.286 F7800
G1 F600
G1 X108.414 Y92.286 E148.90309
;LAYER_CHANGE
;Z:2.4
;HEIGHT:0.8
G1 Z3.4 F600
G1 E146.90309 F2400
G92 E0
G1 X109.2 Y109.2 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:1.6
G1 F600
G1 X90.8 Y109.2 E28.76966
G1 X90.8 Y90.8 E55.53932
G1 X109.2 Y90.8 E82.30898
G1 X109.2 Y109.074 E108.89532
G1 X107.714 Y108.414 F7800
;TYPE:Internal infill
;WIDTH:1.6
G1 F600
G1 X107.714 Y91.586 E133.37917
G1 X106.171 Y91.586 F7800
G1 F600
G1 X106.171 Y108.414 E157.86302
G1 X104.629 Y108.414 F7800
G1 F600
G1 X104.629 Y91.586 E182.34687
G1 X103.086 Y91.586 F7800
G1 F600
G1 X103.086 Y108.414 E206.83072
G1 X101.543 Y108.414 F7800
G1 F600
G1 X101.543 Y91.586 E231.31457
G1 X100 Y91.586 F7800
G1 F600
G1 X100 Y108.414 E255.79842
G1 X98.457 Y108.414 F7800
G1 F600
G1 X98.457 Y91.586 E280.28227
G1 X96.914 Y91.586 F7800
G1 F600
G1 X96.914 Y108.414 E304.76612
G1 X95.371 Y108.414 F7800
G1 F600
G1 X95.371 Y91.586 E329.24997
G1 X93.828 Y91.586 F7800
G1 F600
G1 X93.828 Y108.414 E353.73381
G1 X92.286 Y108.414 F7800
G1 F600
G1 X92.286 Y91.586 E378.21766
M106 S188.7
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.8
G1 Z4.2 F600
G1 E376.21766 F2400
G92 E0
G1 X109.2 Y109.2 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:1.6
G1 F600
G1 X90.8 Y109.2 E28.76966
G1 X90.8 Y90.8 E55.53932
G1 X109.2 Y90.8 E82.30898
G1 X109.2 Y109.074 E108.89532
G1 X108.414 Y107.714 F7800
;TYPE:Internal infill
;WIDTH:1.6
G1 F600
G1 X91.586 Y107.714 E133.37917
G1 X91.586 Y106.171 F7800
G1 F600
G1 X108.414 Y106.171 E157.86302
G1 X108.414 Y104.629 F7800
G1 F600
G1 X91.586 Y104.629 E182.34687
G1 X91.586 Y103.086 F7800
G1 F600
G1 X108.414 Y103.086 E206.83072
G1 X108.414 Y101.543 F7800
G1 F600
G1 X91.586 Y101.543 E231.31457
G1 E229.31457 F2400
G92 E0
G1 X108.414 Y100 F7800
G1 E2 F2400
G1 F600
G1 X91.586 Y100 E26.48385
G1 X91.586 Y98.457 F7800
G1 F600
G1 X108.414 Y98.457 E50.9677
G1 X108.414 Y96.914 F7800
G1 F600
G1 X91.586 Y96.914 E75.45155
G1 X91.586 Y95.371 F7800
G1 F600
G1 X108.414 Y95.371 E99.9354
G1 X108.414 Y93.828 F7800
G1 F600
G1 X91.586 Y93.828 E124.41925
G1 X91.586 Y92.286 F7800
G1 F600
G1 X108.414 Y92.286 E148.90309
;LAYER_CHANGE
;Z:4
;HEIGHT:0.8
G1 Z5 F600
G1 E146.90309 F2400
G92 E0
G1 X109.2 Y109.2 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:1.6
G1 F600
G1 X90.8 Y109.2 E28.76966
G1 X90.8 Y90.8 E55.53932
G1 X109.2 Y90.8 E82.30898
G1 X109.2 Y109.074 E108.89532
G1 X107.714 Y108.414 F7800
;TYPE:Internal infill
;WIDTH:1.6
G1 F600
G1 X107.714 Y91.586 E133.37917
G1 X106.171 Y91.586 F7800
G1 F600
G1 X106.171 Y108.414 E157.86302
G1 X104.629 Y108.414 F7800
G1 F600
G1 X104.629 Y91.586 E182.34687
G1 X103.086 Y91.586 F7800
G1 F600
G1 X103.086 Y108.414 E206.83072
G1 X101.543 Y108.414 F7800
G1 F600
G1 X101.543 Y91.586 E231.31457
G1 X100 Y91.586 F7800
G1 F600
G1 X100 Y108.414 E255.79842
G1 X98.457 Y108.414 F7800
G1 F600
G1 X98.457 Y91.586 E280.28227
G1 X96.914 Y91.586 F7800
G1 F600
G1 X96.914 Y108.414 E304.76612
G1 X95.371 Y108.414 F7800
G1 F600
G1 X95.371 Y91.586 E329.24997
G1 X93.828 Y91.586 F7800
G1 F600
G1 X93.828 Y108.414 E353.73381
G1 X92.286 Y108.414 F7800
G1 F600
G1 X92.286 Y91.586 E378.21766
;LAYER_CHANGE
;Z:4.8
;HEIGHT:0.8
G1 Z5.8 F600
G1 E376.21766 F2400
G92 E0
G1 X109.2 Y109.2 F7800
G1 E2 F2400
;TYPE:External perimeter
;WIDTH:1.6
G1 F600
G1 X90.8 Y109.2 E28.76966
G1 X90.8 Y90.8 E55.53932
G1 X109.2 Y90.8 E82.30898
G1 X109.2 Y109.074 E108.89532
G1 X108.414 Y107.714 F7800
;TYPE:Internal infill
;WIDTH:1.6
G1 F600
G1 X91.586 Y107.714 E133.37917
G1 X91.586 Y106.171 F7800
G1 F600
G1 X108.414 Y106.171 E157.86302
G1 X108.414 Y104.629 F7800
G1 F600
G1 X91.586 Y104.629 E182.34687
G1 X91.586 Y103.086 F7800
G1 F600
G1 X108.414 Y103.086 E206.83072
G1 X108.414 Y101.543 F7800
G1 F600
G1 X91.586 Y101.543 E231.31457
G1 E229.31457 F2400
G92 E0
G1 X108.414 Y100 F7800
G1 E2 F2400
G1 F600
G1 X91.586 Y100 E26.48385
G1 X91.586 Y98.457 F7800
G1 F600
G1 X108.414 Y98.457 E50.9677
G1 X108.414 Y96.914 F7800
G1 F600
G1 X91.586 Y96.914 E75.45155
G1 X91.586 Y95.371 F7800
G1 F600
G1 X108.414 Y95.371 E99.9354
G1 X108.414 Y93.828 F7800
G1 F600
G1 X91.586 Y93.828 E124.41925
G1 X91.586 Y92.286 F7800
G1 F600
G1 X108.414 Y92.286 E148.90309
G1 E146.90309 F2400
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; filament used [mm] = 2674.48
; filament used [cm3] = 2.10
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 3m 16s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = rectilinear
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 0
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 200%
; external_perimeter_speed = 10
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 200%
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "test final"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = 0
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 90
; fill_density = 100%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_height = 0.8
; first_layer_speed = 10
; first_layer_speed_over_raft = 30
; first_layer_temperature = 0
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 0
; gap_fill_speed = 0
; gcode_comments = 0
; gcode_flavor = reprap
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 0
; infill_anchor_max = 0
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 200%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 0
; infill_speed = 10
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.8
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 35
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.84
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 200%
; perimeter_generator = arachne
; perimeter_speed = 10
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = test final
; printer_model = 
; printer_notes = 
; printer_settings_id = test final
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = rear
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 8
; skirt_height = 1
; skirts = 2
; slice_closing_radius = 0
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 10
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 200%
; solid_infill_speed = 10
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 0
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 0
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 1
; threads = 8
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = rectilinear
; top_infill_extrusion_width = 200%
; top_solid_infill_speed = 10
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 10
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 1
; prusaslicer_config = end
